user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    multi_accept        on;
    worker_connections  1024;
}


http {
    charset                utf-8;
    sendfile               on;
    tcp_nopush             on;
    tcp_nodelay            on;
    keepalive_timeout      65;

    server_tokens          off;
    log_not_found          off;
    access_log             off;

    client_max_body_size   16M;

    include                /etc/nginx/mime.types;
    default_type           application/octet-stream;

    absolute_redirect      off;
    port_in_redirect       off;

    include /etc/nginx/conf.d/*.conf;
}